Revert "chore: remove dependabot config"
This reverts commit f278ce1b967ff6c4c116bc36adc1a614b0bd9820, bringing
back dependabot config.

Let's hope this fixes the dependabot issue, which looks like the
following:

    Dependabot can't resolve your Rust dependency files
    Dependabot failed to update your dependencies because there was an error resolving your Rust dependency files.

    Dependabot encountered the following error:

    error: failed to load manifest for workspace member `dependabot_tmp_dir/x509-check/e2e-identity`
    referenced by workspace at `dependabot_tmp_dir/x509-check/Cargo.toml`

    Caused by:
      failed to read `dependabot_tmp_dir/x509-check/e2e-identity/Cargo.toml`

    Caused by:
      No such file or directory (os error 2)